#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_light.sv --exe f1_light_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdelay.mk Vdelay

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vf1_light
echo "\nSimulation completed"


